/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PenHighlighterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  requirePen: true
};
var PenHighlighterPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new PenHighlighterSettingTab(this.app, this));
    this.registerDomEvent(document, "pointerup", (evt) => {
      if (this.settings.requirePen && evt.pointerType !== "pen") {
        return;
      }
      setTimeout(() => {
        this.handleSelection(evt);
      }, 50);
    });
  }
  handleSelection(evt) {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view)
      return;
    const editor = view.editor;
    const selection = editor.getSelection();
    if (!selection || selection.trim() === "") {
      return;
    }
    const x = evt.clientX;
    const y = evt.clientY;
    this.showFormattingMenu(editor, selection, x, y);
  }
  showFormattingMenu(editor, selectedText, x, y) {
    const menu = new import_obsidian.Menu();
    menu.addItem((item) => {
      item.setTitle("1. **ciao** (Grassetto)").setIcon("bold-glyph").onClick(() => {
        editor.replaceSelection(`**${selectedText}**`);
      });
    });
    menu.addItem((item) => {
      item.setTitle("2. *ciao* (Corsivo)").setIcon("italic-glyph").onClick(() => {
        editor.replaceSelection(`*${selectedText}*`);
      });
    });
    menu.addItem((item) => {
      item.setTitle("3. ***ciao*** (Grassetto e Corsivo)").setIcon("highlighter").onClick(() => {
        editor.replaceSelection(`***${selectedText}***`);
      });
    });
    menu.showAtPosition({ x, y });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var PenHighlighterSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Richiedi l'uso della penna").setDesc("Se attivato, il menu apparir\xE0 SOLO quando usi la penna. Se disattivato, apparir\xE0 anche selezionando il testo col dito o col mouse.").addToggle((toggle) => toggle.setValue(this.plugin.settings.requirePen).onChange(async (value) => {
      this.plugin.settings.requirePen = value;
      await this.plugin.saveSettings();
    }));
  }
};
